name: FTP Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy src to html
    runs-on: ubuntu-latest

    steps:
      #  Clonar el repositorio
      - name: Checkout repository
        uses: actions/checkout@v4

      # Subir SOLO la carpeta src a html
      - name: Upload src via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}

          protocol: ftps        # cambia a ftp si no usas ftps
          port: 21
          passive: true

          # folders
          local-dir: ./src/
          server-dir: /html/
