name: Deploy via SFTP


#desplige manual
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Entorno a desplegar'
        required: true
        default: 'production'
      reason:
        description: 'Motivo del deploy'
        required: false

#despliegue automatico
#on:
#  push:
#   branches:
#      - main
      
      
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - run: |
          composer install
          vendor/bin/phpunit

      - name: Upload files
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: "src"
          target: "/var/www/html"
